
version: '3.9'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: webdb2024
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  node_app:
    build:
      context: ./gcshop
    container_name: node_app_container
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: webdb2024
    depends_on:
      - mysql

volumes:
  db_data:
